# Generated by Django 5.1.7 on 2025-03-18 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
    ]
